[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
# optimizer = true
# optimizer_runs = 200 
solc_version = "0.8.25"

# Gas reporting
gas_reports = ["*"]
gas_limit = 9223372036854775807

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15, fail_on_revert = false }

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

# Network configurations
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
