[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
# optimizer = true
# optimizer_runs = 200 
solc_version = "0.8.25"


remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

# Network configurations
[rpc_endpoints]
etherlink = "https://node.ghostnet.etherlink.com"

[etherscan]
etherlink = { key = "${ETHERLINK_API_KEY}", url = "https://testnet.explorer.etherlink.com/api" }

