[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

[profile.ci]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
gas_reports = ["*"]
gas_reports_ignore = ["forge-std/*"]
fuzz_runs = 1000
verbosity = 4

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
