name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci
  FOUNDRY_DISABLE_NIGHTLY_WARNING: 1

jobs:
  check:
    name: Foundry Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Show Forge version
        run: forge --version

      - name: Install dependencies
        run: forge install

      - name: Check formatting
        run: forge fmt --check

      - name: Build with Forge (ignore size exit code)
        run: |
          forge build --sizes || {
            echo "::warning title=Contract Size Limit::Some contracts exceed the 24KB EIP-170 size limit.";
          }

      - name: Run Forge tests
        run: forge test -vvv